name: Docker Deploy (Development)

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  docker-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do repositório
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Configurar JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # 3. Instalar Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # 4. Carregar Variáveis do Arquivo .env.ci
      - name: Load Environment Variables
        run: |
          set -o allexport
          source .env.ci || true
          set +o allexport

      # 5. Login no Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6. Build da Imagem Docker
      - name: Build Docker Image
        run: |
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/vaideferry-backend:dev .

      # 7. Push da Imagem para o Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/vaideferry-backend:dev
