name: Test Docker Deploy

on:
  push:
    branches:
      - renef/test_deploy

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do repositório
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Configurar JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # 3. Instalar Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # 4. Carregar Variáveis do Arquivo .env
      - name: Load Environment Variables
        run: |
          set -o allexport
          source .env || true
          set +o allexport

      # 5. Login no Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6. Build da imagem Docker
      - name: Build Docker Image
        run: |
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/unidesk:renef-test .

      # 7. Push da imagem para o Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/unidesk:renef-test

      # 8. Rodar o Docker Compose
      - name: Run Docker Compose
        run: |
          docker-compose --env-file .env up -d
